### ISSUE TITLE
Deprecation of Global HTTP Batch Endpoint

### ISSUE THREAD

**Issue by ZYinMD** [google/google-api-javascript-client#584] opened 2019-12-13 05:49 UTC
I received an email from `Google Developers Team` which informed me that:

1. `Global HTTP Batch Endpoints` will be shut down
2. I'm receiving this email because one of my projects is hitting such endpoints
3. more details can be found in [this blogpost][1]

So I read the blogpost, and found that "homogeneous batch requests" will still be supported. Well I do think that all my batch requests are homogeneous, because they're all sent to the [tasks API@v1][2], but I still received this email. Am I going to be impacted?

(one guess I have is that my batch contains different methods and different endpoints, but I'm not sure if that counts as heterogeneous if they're sent to the same API)

Thanks!

*  *  *  
![image](https://user-images.githubusercontent.com/32368482/70772276-f93fa900-1d41-11ea-806b-de0c7caca6bf.png)

[1]: https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html
[2]: https://developers.google.com/tasks/v1/reference

**Comment by MathiasGilson** [comment] 2019-12-14 08:00
If you read the section **HTTP batch** on the [blog post ](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html) it's pretty clear that they define a heterogeneous batch request as a request sent to 2 differents api.
As long as you are sending request to only 1 api I'm pretty sure that it's gonna keep working as intended

here is the migration guide in the blog post if you ping multiple apis

BEFORE


```javascript
// heterogeneous batch request example.
// Notice that the outer batch request contains inner API requests
// for two different APIs.

// Request to urlshortener API
request1 = gapi.client.urlshortener.url.get({"shortUrl": 
"http://goo.gl/fbsS"});

// Request to zoo API
request2 = gapi.client.zoo.animals.list();

// Request to urlshortener API
request3 = gapi.client.urlshortener.url.get({"shortUrl":
"https://goo.gl/XYFuPH"});

// Request to zoo API
request4 = gapi.client.zoo.animal().get({"name": "giraffe"});

// Creating single heterogeneous batch request object
heterogeneousBatchRequest = gapi.client.newBatch();
// adding the 4 batch requests
heterogeneousBatchRequest.add(request1);
heterogeneousBatchRequest.add(request2);  
heterogeneousBatchRequest.add(request3);
heterogeneousBatchRequest.add(request4);
// print the heterogeneous batch request
  heterogeneousBatchRequest.then(x=>console.log(x));
```

AFTER


```javascript
// Split heterogeneous batch request into two homogenous batch requests

// Request to urlshortener API
request1 = gapi.client.urlshortener.url.get({"shortUrl": "http://goo.gl/fbsS"});

// Request to zoo API
request2 = gapi.client.zoo.animals.list();

// Request to urlshortener API
request3 = gapi.client.urlshortener.url.get({"shortUrl": "http://goo.gl/fbsS"})

// Request to zoo API
request4 = gapi.client.zoo.animals.list();

// Creating homogenous batch request object for urlshorterner
homogenousBatchUrlshortener = gapi.client.newBatch();
// adding the 2 batch requests for urlshorterner
homogenousBatchUrlshortener.add(request1); 
homogenousBatchUrlshortener.add(request3); 

// Creating homogenous batch request object for zoo
homogenousBatchZoo = gapi.client.newBatch();

// adding the 2 batch requests for zoo
homogenousBatchZoo.add(request2); 
homogenousBatchZoo.add(request4);
// print the 2 homogenous batch request
Promise.all([homogenousBatchUrlshortener,homogenousBatchZoo])
    .then(x=>console.log(x));

```

**Comment by ZYinMD** [comment] 2019-12-14 15:21
Thanks @MathiasGilson , yes I thought so too, but my concern is why I received this email. It claimed to have detected that I'd be affected. I wonder if they send the warning to anyone who's batching, or only to the ones who's batching heterogeneous requests.

**Comment by MathiasGilson** [comment] 2019-12-17 12:07
Good question, which version of gapi are you using ?

**Comment by ZYinMD** [comment] 2019-12-17 14:22
I'm using `https://apis.google.com/js/client.js`. 

(It's the only version I know of, is it the recommended way to use it?)

**Comment by MathiasGilson** [comment] 2019-12-18 08:10
Yeah same for me, I checked the batch endpoint have been correctly updated so it should be ok
Not sure why you received this email

**Comment by ZYinMD** [comment] 2019-12-21 05:38
Thanks, what did you mean by "checked the batch endpoint have been correctly updated"? Where did you check?

**Comment by MathiasGilson** [comment] 2019-12-24 05:11
You can check the requested url on the chrome dev tools under "Network"
Just make a request and check that the url for a batch request is not the global one but the one for the tasks api

**Comment by ZYinMD** [comment] 2019-12-24 05:53
Ah, I see. Unfortunately I checked and my batch was indeed sent to the global endpoint. I guess it's because I didn't use the discovery doc, I just used the rest endpoints, it's easier because they align with all my Postman tests.

I guess `batch` doesn't know all my requests are homogeneous if I just use the rest endpoints.

**Comment by MathiasGilson** [comment] 2019-12-25 11:12
Yes be sure to use the `batch/tasks/v1` endpoint and you should be good 😉

**Comment by Jahdrien** [comment] 2020-03-24 16:58
Hi,
I have the same problem here : with Calendar API loaded using discovery doc url (https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest) which contains the right batch path ("batchPath": "batch/calendar/v3"), my homogenous batch requests are still sent to the deprecated global batch endpoint...
Do you have a solution while we wait for an update of the library ?

**Comment by AVapps** [comment] 2020-08-01 09:49
I have found the solution, thanks to this [comment](https://github.com/google/google-api-javascript-client/issues/650#issuecomment-651946045) in issue #650 : batch requests are sent to the right batch endpoint when you create an homogeneous endpoint using generated API. I used gapi.client.request({ path: ... }).

**Comment by jsonx** [comment] 2020-08-19 12:59
Hi,
My all calendar requests was homogeneous and made by Calendar Service Class and still getting "global http batch endpoint is deprecated" exception. I have changed 
`const BATCH_PATH = 'batch' to "batch/calendar/v3"`
in "vendor/google/apiclient/src/Google/Http/Batch.php" file and everything works now

**Comment by sjordan1975** [comment] 2020-08-20 08:07
@jsonx 

Rather than changing vendor code (which is likely to get lost if you update with composer), you can pass the batch patch as a parameter when creating an instance of the class.

Class signature:
```
// assumes you've declared $class var earlier
$batch = new Google_Http_Batch($client, false, null, 'batch/calendar/v3');
```

**Comment by dvanderb** [comment] 2021-03-29 23:08
This deprecation has been completed. I am closing this for now, but if you still need help with this question, please reopen.

**Closed by dvanderb** 2021-03-29 23:08 UTC
