### ISSUE TITLE
GoogleAuth.signOut() does not sign out from Google

### ISSUE THREAD

**Issue by SGYUM** [google/google-api-javascript-client#419] opened 2018-04-12 09:36 UTC
I am able to use "Login with Google" successfully and now trying to implement Logout from Google using below standard Google javascript SDK for logout. It executes without any error and displays "User signed out" but does not logout user from gmail (or any google signed in in another tab ). How to logout a user from Google itself?
<html>
<script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
</br>
<script>   
function init() {</br>
  gapi.load('auth2', function() { </br>
	// Ready. </br>
	gapi.auth2.init(</br>
	{</br>
  	client_id: 'deleted'</br>
	});</br>
});</br>
}</br>
  function googleLogout() {

	    alert("googleLogout start");
	    //gapi.auth2.getAuthInstance().signOut();
	    //OR (both are same)
	    var auth2 = gapi.auth2.getAuthInstance();
    	    auth2.signOut().then(function () {
           	console.log('User signed out.');
    	   });   
	    alert("googleLogout done."); 
    }      

</script>
</html>

**Comment by kongguibin** [comment] 2018-04-12 22:39
From the documentation: https://developers.google.com/identity/sign-in/web/sign-in#sign_out_a_user, the signOut() method enables users to sign out of your app without signing out of Google.

From Google's point of view, a third party app should not force Google to clear its session. End user can do that on google.com if he likes.

**Comment by kongguibin** [comment] 2018-04-12 22:41
Close this issue, since it works as intended.

**Closed by kongguibin** 2018-04-12 22:41 UTC

**Comment by kotAPI** [comment] 2018-07-13 11:05
@kongguibin but facebook has an opposite view right? from their point of view, an app should leave them the way they are prior to logging into the third party app

**Comment by hostbrook** [comment] 2018-08-03 20:57
I have the same issue. Looks like kongguibin is right. And yes, Facebook has an opposite view.

**Comment by kotAPI** [comment] 2018-08-08 07:10
Didn't work for me @hostbrook , after hours of searching I realized that all Oauth services don't log off from their respective platforms on signOut. It's upto the user to log off from the platform they logged-in from. Try doing it on an incognity, say Google OAuth, Even after signing out, open a new tab and check out gmail.com or something, you'd still be logged in. 

This unfortunately is the standard behaviour on any OAuth

**Comment by mastronardif** [comment] 2018-10-14 15:12
I have the same problem.  Maybe I don't understand the issue but here is my situation. I have an app the user logs in.  Now I want the user to logout and a have another (different) user log in.  This does not work. 
The first users is always logged in.  It kinda works in incognito and FF.  What would happen if the a user runs the app from a public library computer.

**Comment by kotAPI** [comment] 2018-10-15 04:12
@mastronardif it rests on the user to go to the platform website and safely log off. OAuth logins aren't safe meant for public computers. They're there so the users can skip the hassle of filling up pages of sign up forms. 

Logging off from the parent app won't logoff the user from the platform itself. I've spent days and nights about this behaviour thinking it was a bug on my side. Not to worry, it's a default behavior.  To protect your users and keep them informed, maybe you can add a note saying they should log off from their respective platforms once they're done using the app if its a public computer. It definitely is a huge risk and I'm surprised the OAuth standard didn't consider this.

**Comment by acenspades** [comment] 2019-09-10 21:56
Hello
I have the same issue. I've implemented Google Sign In SDK and I'm using [[GIDSignIn sharedInstance]signout]; to log a user out.  It is bound to a button.  My question is, why is there even a GIDSignIn signout if it doesn't sign the user out of Google?

**Comment by yanamal** [comment] 2020-09-10 19:47
> The only reason `gapi.auth2.getAuthInstance().signOut()` exists is to allow to switch between users:

This is precisely what I was trying to use signOut() for, and for me, it is not working (googling led me to this page).

 It does *someting*, because next time on sign-in, the google flow redirects a couple more times. But **it does not allow me to switch accounts**. It just automatically logs into the account I chose the first time around. I only ever see that "Choose an account" screen once, until I clear all cache and cookies (which _does_ sign me out of my Google account, btw)

Why? how do I make it work?

**Comment by MumblingFumbler** [comment] 2021-01-09 18:48
gapi.auth2.getAuthInstance().signOut()  might work 'as designed', but it does not work 'as expected'. If it works as designed then why provide a sample that clearly illustrates 'works as expected', although it doesn't work.
See:
https://github.com/google/google-api-javascript-client/blob/master/samples/authSample.html
This code does not work.
signOut() is called, does not return an error, does not sign out, and does not call  the listener, updateSigninStatus(). The only way to reset the signIn is by going to a google page and signing out.
Unless you want developers to chase their tails trying to figure out what's wrong, or write bug reports, I suggest you remove the sample code, or annotate it, or fix it so that it does work. I notice that it has a 2011 copyright--maybe it worked correctly back then?

**Comment by evil-shrike** [comment] 2021-03-15 11:40
Thanks, @yanamal  for the hint with ` prompt: 'select_account'` it really helps. As w/o it with default behavior signIn/signOut don't allow you to switch accounts. Unfortunetely Google Sign-In button doesn't seem to support this mode (the prompt option):
```
    gapi.signin2.render('signin-btn', {
      'scope': 'profile email',
      'width': 240,
      'height': 50,
      'longtitle': true,
      'theme': 'dark',
      'onsuccess': this.onSuccess.bind(this),
      'onfailure': this.onFailure.bind(this)
    });
```

**Comment by yanamal** [comment] 2021-03-15 22:09
>  Unfortunetely Google Sign-In button doesn't seem to support this mode (the prompt option):

Yeah, I had to cobble together the Google-approved-looking button manually across my HTML+CSS+JSS instead of relying on the render function to generate one properly.

Honestly, I don't even remember where I dug up examples of how to do it, but you can roughly see how I did it in my code here:
https://github.com/yanamal/DocPrompter/search?q=googleSignIn

**Comment by Arijit0** [comment] 2021-09-01 06:48
> gapi.signin2.render('signin-btn', {
>       'scope': 'profile email',
>       'width': 240,
>       'height': 50,
>       'longtitle': true,
>       'theme': 'dark',
>       'onsuccess': this.onSuccess.bind(this),
>       'onfailure': this.onFailure.bind(this)
>     });



gapi.signin2.render('signin-btn', {
      'scope': 'profile email',
      'width': 240,
      'height': 50,
      'longtitle': true,
       prompt: 'select_account',
      'theme': 'dark',
      'onsuccess': this.onSuccess.bind(this),
      'onfailure': this.onFailure.bind(this)
    });

prompt: 'select_account', Working fine. Please check

**Comment by eyedean** [comment] 2021-10-06 17:56
> > gapi.signin2.render('signin-btn', {
> > 'scope': 'profile email',
> > 'width': 240,
> > 'height': 50,
> > 'longtitle': true,
> > 'theme': 'dark',
> > 'onsuccess': this.onSuccess.bind(this),
> > 'onfailure': this.onFailure.bind(this)
> > });
> 
> gapi.signin2.render('signin-btn', { 'scope': 'profile email', 'width': 240, 'height': 50, 'longtitle': true, prompt: 'select_account', 'theme': 'dark', 'onsuccess': this.onSuccess.bind(this), 'onfailure': this.onFailure.bind(this) });
> 
> prompt: 'select_account', Working fine. Please check

Confirmed that `data-prompt="select_account"` works in the render view: 🎉 

```html
<div
	data-width="185"
	data-longtitle="true"
	class="g-signin2"
	data-prompt="select_account"
	data-onsuccess="onGoogleSignIn"
	data-onfailure="onGoogleFailure"
	data-theme="dark"
></div>
```

**Comment by pradeep-orbi** [comment] 2022-05-31 16:47
> > The only reason `gapi.auth2.getAuthInstance().signOut()` exists is to allow to switch between users:
> 
> This is precisely what I was trying to use signOut() for, and for me, it is not working (googling led me to this page).
> 
> It does _someting_, because next time on sign-in, the google flow redirects a couple more times. But **it does not allow me to switch accounts**. It just automatically logs into the account I chose the first time around. I only ever see that "Choose an account" screen once, until I clear all cache and cookies (which _does_ sign me out of my Google account, btw)
> 
> Why? how do I make it work?
> 
> Edit: I found I had to force account-selection by passing options to signIn():
> 
> ```js
> gapi.auth2.getAuthInstance().signIn({
>     prompt: 'select_account'
> });
> ```

How to achieve this in android ?
