### ISSUE TITLE
gapi.auth.authorize does not close the popup

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#74] opened 2015-01-07 01:37 UTC
_From [supp...@stacktype.com](https://code.google.com/u/109365404105658033239/) on March 09, 2013 00:05:19_

What steps will reproduce the problem? If possible, provide a live demo of the issue. 1.Use the gapi.auth.authorize to start google authorization using javascript in a chrome extension.
2.Shows the authorization screen to user with accept/deny.
3.After hitting accept, the popup goes blank and does not close. This is although authorization has succeded in the background. What is the expected output? What do you see instead? Expect the authorization popup to close after hitting 'Accept' on authorization popup. What version of the product are you using? On what operating system? Chrome 25.01, Windows 7, javascript api from here - https://code.google.com/p/google-api-javascript-client/wiki/GettingStarted Please provide any additional information below. The above issue occurs in a chrome extension. Also, I have setup my API access correctly in google API console correctly. I have specified javascript origin - "chrome-extension://<extension id>" and left the redirect uri blank.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=74_

**Comment by trustedjohn** [comment] 2015-04-19 05:33
Was this ever fixed?  I'm experiencing this problem from a InAppBrowser plugin from Phonegap under iOS.  Following google auth examples to the letter but child browser window never closes after auth.

**Comment by Latchumi** [comment] 2015-05-27 12:11
Hi,
Even I was getting same issue in app built by cordova. And also in windows mobile and IE metro it was not closing the window. To make it work everywhere, I just did a workaround. Instead of calling gapi.auth. apis, I opened the url with all the required parameters by window.open(assign the window object to some variable, will be used while closing the window). Handle the response on redirect uri and close the window using the variable. It works well in all devices. Checked in kindle, windows, iphone, IE metro desktop, IE desktop, chrome, safari.

**Comment by msolomonTMG** [comment] 2015-12-13 01:56
+1

**Comment by lambrospetrou** [comment] 2015-12-16 01:12
This problem of the window not closing still exists with Chrome extensions...

**Comment by bsittler** [comment] 2015-12-16 02:08
I'm not aware of any way to solve it.

**Comment by Vovan-VE** [comment] 2016-02-04 04:16
Still failing in Chrome and Opera (Webkit at all?) when using client side OAuth2. Works in FF and IE.
But I'm using HTTP - not HTTPS. Cannot check with HTTPS currently.

https://developers.google.com/api-client-library/javascript/samples/samples

> Note: All samples are HTTPS only.

**Comment by Vovan-VE** [comment] 2016-02-04 06:16
I found my mistake. I did initiate authentication in debug mode with non-human event, which blocks a popup. Thats why google OAuth popup didn't want to close in Chrome and Opera itself in my case. After I moved authentication in human's event (click), the popup started to work properly.

(It whould be nice, if Webkit said in console something like "this window is not allowed to close itself")

**Comment by TMSCH** [comment] 2017-02-17 18:40
Cordova/PhoneGab and Chrome Extensions are not supported environments by our JavaScript library.

The first two are very tricky to support and would require specific Cordova plugins to be installed to properly handle opening a browser view and closing it. I would recommend trying to look for Cordova plugins specifically for Google Sign-In.

The Chrome Extension environment also has many constraints that make it difficult to support properly. And for this environment, [chrome.identity](https://developer.chrome.com/apps/identity) provides a way to get access tokens.

Closing this issue as intended behavior.

**Closed by TMSCH** 2017-02-17 18:40 UTC
Labels: 21+ stars, bug, imported, Priority-Medium
