### ISSUE TITLE
Can google ApI client  be used from Chrom extensions?

### ISSUE THREAD

**Issue by kavithaLK** [google/google-api-javascript-client#261] opened 2016-12-24 06:02 UTC
I am trying to invoke google app engine from a chrom extensions JS file. but i am not able to go through init mehod. Not able to get the error too. WHat is that has to be done ?Is it supported from extension?

**Comment by bsittler** [comment] 2016-12-27 19:57
Thanks for the question, but I think I do not understand completely. What do you mean by "invoke Google AppEngine" exactly? And when you say "JS file" do you refer to the background page, a content script, or something else?

Also, Chrome extensions are not among the supported environments listed here: https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments

This means it might or might not work, and even if it does work you are pretty much on your own support-wise. That said, searching a bit showed evidence that some people did get it working: http://stackoverflow.com/questions/18681803/loading-google-api-javascript-client-library-into-chrome-extension

**Comment by bsittler** [comment] 2016-12-28 17:10
This is a duplicate of https://github.com/google/google-api-javascript-client/issues/64

**Closed by bsittler** 2016-12-28 17:10 UTC
Labels: duplicate
