### ISSUE TITLE
onload function getting triggred befor window.gapi.client is available.

### ISSUE THREAD

**Issue by samdeepk** [google/google-api-javascript-client#797] opened 2022-03-08 17:09 UTC
We are still using a legacy system to load google cloud endpoints API.

https://apis.google.com/js/client:platform.js?onload=

we are trying to call window.gapi.client.setApiKey after the onload function is called by client:platform.js. There are not changes made to the code recently but in the past few days by time onload function is called window.gapi seems to be defined and window.gapi.client is not defined. 

This has been causing major issues with legacy systems deployed and affecting 1000s of active users. you can see the error in console of our staging https://manabadi-staging.appspot.com/app/#!/login

**Comment by dvanderb** [comment] 2022-03-08 19:58
As we debugged more we discovered that double loading is not in fact the issue here and we're working on a fix for the root cause(should be fixed today). In the interim you'll have to ensure client is loaded before making calls in your callback. If you are able to change the url in the angular module you are using to just `client.js` from `platform:client.js` then that should solve the problem for you(I am not 100% sure but based on your obfuscated code I don't think you need platform).

**Comment by samdeepk** [comment] 2022-03-08 23:54
It's a legacy system with broken deployment process. It's hard to change anything now. If it could be fixed on library that would be very helpful.

**Comment by dvanderb** [comment] 2022-03-09 06:12
We have a fix that will roll out over the next day or so.

**Comment by dvanderb** [comment] 2022-03-10 20:10
The fix for this was rolled out and your application should be working properly.

**Closed by dvanderb** 2022-03-10 20:10 UTC
