### ISSUE TITLE
Do I understand the "multiple client ids" scenario for advanced usage correctly

### ISSUE THREAD

**Issue by BigYu** [google/google-api-javascript-client#294] opened 2017-05-09 13:38 UTC
My single page applications have more than 1 routes requires the google access by signing in with **different client ids**. Some other tabs are likely to request google permissions from web server. Does it mean it qualifies to the advanced usage?

I read the points from your doc and will appreciate your help to confirm I understand it correctly :D

>>> - Your application only needs to requests a Google API endpoint once, for instance to load the user's favorite YouTube videos the first time they sign in.
>>> - Your application has its own session management infrastructure, and it only requires the ID Token once to identify the user in your backend.
>>> - Several Client IDs are used within the same page.

**Comment by TMSCH** [comment] 2017-05-09 17:38
Hi @BigYu, from my understanding it seems to be your scenario indeed. The `init/signIn` behavior will only allow you to have *one client ID per app*, and the sign-in state will be synced *across tabs*.

`gapi.auth2.authorize` will not sync state and allows to specify a different client ID for each call.

However, using multiple client IDs for one app has to be done in last resort. It is not user friendly as the user has to authorize each client ID separately. It is generally better, when possible, to use [incremental auth](https://developers.google.com/identity/sign-in/web/incremental-auth).

Let me know if that helps!

**Comment by BigYu** [comment] 2017-05-10 10:08
@TMSCH Thanks for your explaining. I will try the advanced api first. Below is what I did:

```javascript
    gapi.auth2.authorize({
      'client_id': ‘.apps.googleusercontent.com',
      scope: 'email’,
      'response_type': 'code',
      'prompt': 'select_account',
      'cookie_policy': 'none',
      'include_granted_scopes': false,
    }, (response) => {
      if (response.error) {
        // An error happened!
        return;
      }
      const GoogleAuth  = gapi.auth2.getAuthInstance();
      const user = GoogleAuth.currentUser.get();  // here I met an issue

      // code...
    });
```

**gapi.auth2.getAuthInstance()**; returns undefined, could you pls let me know if it can be used together with authorize?

**Comment by BigYu** [comment] 2017-05-10 13:22
@TMSCH Btw, you told me that ```gapi.auth2.authorize``` does not sync status. But what I saw is: one of my scenario signs in from web-server successfully, another scenario which uses gapi.aut2.authorize and a different client id signs in silently without popup. It seems the state is synced, any ideas about this scenario?

**Comment by TMSCH** [comment] 2017-05-10 16:28
@BigYu `gapi.auth2.getAuthInstance()` is not defined when using `gapi.auth2.authorize`. Only when using `init`/`signIn` (this is because there is not a singleton GoogleAuth instance available in that case, as required for multiple client IDs). Sorry if that wasn't clear.

In your scenario with the silent popup sign-in, are you saying that the user had not authorized that specific client ID before? Even during another session?

**Comment by BigYu** [comment] 2017-05-11 14:06
@TMSCH Sorry that I didn’t make it clear.

What I saw is:

1. In a new incognito window,  sign in first from a scenario which uses web-server auth, then go to another scenario, sign in using client-side auth: ```gapi.auth2.authorize({ …’prompt’: ‘select-account’})``` with a totally different client Id (the client id wasn’t signed in before), the sign-in window popups but closes automatically and quickly. My question is: since I set the prompt: **‘select-account**’, why doesn’t it allow me to sign in with another account?

2. After above scenario, sign in with a different account in another app, then goes back to my app,  click the ‘sign in’ button which uses client-side ```gapi.auth2.authorize auth```, the sign in window pops up and let me choose one of the two available accounts. 

I have two questions:

1. Since I set ```‘prompt’ : ‘select-account’```,  what I expect is: the sign in popup always shows up, even when I signed in with the same account before or in current session.
2. Does ```gapi.auth2.authorize``` provide logout method? How can my software revoke end users' Google permission?

**Comment by TMSCH** [comment] 2017-05-11 18:41
1. Try `select_account` instead of `select-account` there is a typo in your parameter's value.
2. `gapi.auth2.authorize` does not provide logout method as it doesn't "sign in" a user, only authorize it and fetch an access token. Currently, you can only revoke the user's permission using the library if you use the common `init/signIn` flow, and then [`GoogleUser.disconnect`](https://developers.google.com/identity/sign-in/web/reference#googleuserdisconnect).

**Comment by BigYu** [comment] 2017-05-12 02:36
My apology, 'select-account' is a typo in above issue description, it is correct in our code which is 'select_account' as in Google API doc

**Comment by TMSCH** [comment] 2017-05-12 16:25
@BigYu I was able to reproduce the bug. The `'select_account'` value is indeed ignored, and your expectation of the behavior is correct. We will address the issue and keep you updated!

**Comment by TMSCH** [comment] 2017-06-30 20:57
@BigYu the fix has been deployed. Let me know if that works!

**Comment by mesqueeb** [comment] 2018-04-04 14:00
@TMSCH 
Sorry to post on an old thread. But it was still open and I have exactly the question as the title of the thread!

if I do `gapi.auth2.authorize` to authorize a user for e.g. calendar access.
However the user has a google account who he also has given access to the calendar.
Do I need to call a silent `gapi.auth2.authorize` without prompt with the email address as `login_hint` before every API call, or do I need to use `gapi.client.setToken(tokenObject)`?

**Comment by TMSCH** [comment] 2018-04-04 16:36
I'm not sure to understand, how would you get the token in the second case?

It's better to call `gapi.auth2.authorize` anyway to make sure to have a fresh token. The token used by `gapi.client` will be automatically set.

**Closed** 2018-04-04 16:36 UTC

**Comment by mesqueeb** [comment] 2018-04-04 18:11
@TMSCH I'm just using the following in both cases. (I'm not using the `init/signIn` flow, only authorize.)
```js
config.prompt = 'none'
config.login_hint = email
window.gapi.auth2.authorize(config, function (response)...
```
So I would save the calendar `email` in my server's DB.

But after `authorize`ing the gapi client twice, once for each email address, every time I want to patch an event or something how do I make sure the client is switched to that account?

Should I use `gapi.client.setToken(tokenObject)` before each api call like `patch` or `events.list` etc?

Best regards.

**Comment by TMSCH** [comment] 2018-04-04 18:52
If you switch the accounts frequently, you are correct, it's best to `setToken` with the correct token before each call to the API.
