### ISSUE TITLE
popup_closed_by_user when requesting email scope in IE 11

### ISSUE THREAD

**Issue by mkonars** [google/google-api-javascript-client#309] opened 2017-06-17 11:51 UTC
Hi,
I am using your sample from here:
https://github.com/google/google-api-javascript-client/blob/master/samples/authSample.html

May be similiar to:
https://github.com/google/google-api-javascript-client/issues/293

When I call  gapi.client.init() and specify email scope in IE11 I get error "popup_closed_by_user".
In Chrome it works ok.
If I just set 'profile' scope it's also ok.

Could you help with this?

**Comment by TMSCH** [comment] 2017-06-19 17:13
@mkonars I am not able to reproduce the issue with IE11 on Windows 10, using the exact code in authSample.html besides the `scopes` variable that I set to `'email'`. Are you using the exact same code too? If not (or if you made several updates), can you post the snippet of code you're using?

**Comment by mkonars** [comment] 2017-06-19 20:13
Hi @TMSCH 
Thank you for answer.

Now I think that this is not related to your library. I have created a jsfiddle with this code and the issue is not there. But when I host it on IIS I get this error. However on my private machine I get this error even with 'profile' scope. On my work machine I get this only for 'email' scope. And the issue it only with IE.

I will try to look more into it .

PS: Is it possible to get an unminifed version of the library?

**Comment by TMSCH** [comment] 2017-06-19 21:09
@mkonars ok let me know what you find. This is currently not possible to get an unminified version.

**Comment by TMSCH** [comment] 2017-06-30 20:44
Closing the issue, reopen if you find that the bug comes from the library.

**Closed by TMSCH** 2017-06-30 20:44 UTC

**Comment by mkonars** [comment] 2017-07-05 08:18
Hi,
I found that the problem is related to IE11 settings and cache. 

You have to go to Internet Options -> Browsing History Settings -> Caches and databases -> and check Allow website caches and databases

After this, you have to clean the cache:
go to Internet Options -> Browsing History Delete - > delete cookies and temporary files

**Comment by TMSCH** [comment] 2017-07-05 16:54
Thanks @mkonars for finding the root cause of this problem. We haven't observed issues with the default config of IE11 so the impact is very limited.
