### ISSUE TITLE
Fitness API calls never return

### ISSUE THREAD

**Issue by timbarclay** [google/google-api-javascript-client#667] opened 2020-08-27 15:30 UTC
I've attempted to follow the Getting Started instructions closely to make a GET request to the Fitness API

```javascript
<script src="https://apis.google.com/js/api.js"></script>
<script>
  function start() {
    gapi.client.init({
      'apiKey': 'my api key here',
      'discoveryDocs': ['https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest']
    }).then(function() {
      return gapi.client.fitness.users.dataSources.list({
        userId: "me",
        dataTypeName: "com.google.activity.exercise"
      });
    }).then(function(response) {
      console.log(response.result); // This never gets called
    }, function(reason) {
      console.log('Error: ' + reason.result.error.message); // And neither does this
    });
  };
  gapi.load('client', start);
</script>
```

The client loads and initialises successfully and, having done so, `gapi.client` contains a `fitness` property containing all the various objects and functions I would expect.

However calling them doesn't seem to do anything. As noted in the comments in the code above, neither the response nor error callbacks are executed. There are also no errors or anything printed to the console.

**Comment by zarend** [comment] 2020-09-12 18:22
Hi @timbarclay, I copied the code sample above and added my own apiKey, and I was able to reproduce the silent failure behavior. The gapi calls to `gapi.client.fitness.users.dataSources.list` was a no-op as far as I could tell; there were no errors in the console and no failed network requests.

This is happening because the fitness API requires using oauth 2.0 (see https://developers.google.com/fit/rest/v1/authorization).

To correctly use oauth 2, we need to pass `clientId` and `scope` to `gapi.client.init`. Please see the Auth guide for more details.
https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md

Hopefully this helps, good luck.

**Comment by dvanderb** [comment] 2021-03-29 21:23
Hopefully the previous comment helped with this issue. I am closing this for now, but if you still need help with this question, please reopen.

**Closed by dvanderb** 2021-03-29 21:23 UTC
