### ISSUE TITLE
Getting `popup_closed_by_user` after navigating to an external URL and coming back

### ISSUE THREAD

**Issue by sevagsim** [google/google-api-javascript-client#377] opened 2017-12-19 00:15 UTC
I am using React, but the basic usage of this API that I have is:

```
gapi.load('client:auth2', () => {
        gapi.client.init({
          apiKey: config.googleApiKey,
          clientId: config.googleClientId,
          scope: 'openid email',
        });
      });
```

After that, I have the following code:

```
gapi.auth2.getAuthInstance().signIn({ prompt: 'select_account' }).then(this.onSignIn, this.onSignInError);
```

This works fine in a normal scenario, but...

Steps to reproduce the issue I am having are as follows:

1. Login via Google oAuth
2. Type in address bar a URL that is something external (not my domain)
3. Click browser back button
4. Log out of my site
5. _Attempt_ to log back into my site...

At this point, I receive  the error `popup_closed_by_user` after clicking on the user I would like to login with on the google prompt with list of my google accounts.

Sometimes the error does not happen on first repetition of steps above, but for sure on the 2nd repetition it will happen.

** NOTE **

This does not occur in Safari or Firefox, this issue _only_ exists in Chrome.  I tried Chrome versions 59 - 63, and they all have the same issue.

**Comment by aofzazsex5aofzazGithub** [comment] 2018-01-04 07:23
Good

**Comment by TMSCH** [comment] 2018-01-10 15:46
Hi @sevagsim, I tried on Chrome 63 on my Macbook and cannot reproduce the issue. It seems like a pretty edge case too, if you have to do twice the whole process.

**Comment by AndrewRevinsky** [comment] 2018-02-21 22:04
It seems that upon selection of a user, the dialog does its querying and then, does `setTimeout(..., 1000)`. Where the error is initially thrown from. Apparently, the querying time (and perhaps Chrome's debugger routines slowing it even more) exceeds the 1 second, so instead of a normal operations flow, the `user_closed..` kicks in.

In my environment, Mac Os, Chrome 64, everything works normally if Dev Tools are not open.

**Comment by TMSCH** [comment] 2018-02-21 22:48
@AndrewRevinsky the library assume that after the popup is closed, the message is sent from the popup to the main window within 1sec. I'm surprised it would take more than that when the console is opened.

**Comment by tzabarc** [comment] 2018-03-28 11:22
what if the network is really slow? like the devtools network simulation "Slow3G"

**Comment by TMSCH** [comment] 2018-03-28 19:31
@tzabarc the 1sec timeout is not for a network request but for a postMessage.

**Comment by dustinkerstein** [comment] 2018-07-24 15:57
Any updates on this? I can replicate something very similar on Android Chrome (haven't seen it in Windows Chrome). If I stay on the Google account picker for > 1 second I get this error.

**Comment by kongguibin** [comment] 2018-10-18 04:04
This bug should be fixed. More detail at: https://github.com/google/google-api-javascript-client/issues/405

**Closed by kongguibin** 2018-10-18 04:04 UTC
