### ISSUE TITLE
Google Signin with hosted domains

### ISSUE THREAD

**Issue by PDSBGreg** [google/google-api-javascript-client#267] opened 2017-01-20 20:26 UTC
I've been using the following Google Sign In code for about a year without a problem. Then, as of Tuesday January 17th, when signing in via mobile devices, the hosted_domain property is completely ignored, which allows any email address to be added as the first step. For non mobile devices (PCs, Macs, laptops, etc), the hosted domain is enforced and the user is auto-directed to our federated login server.

```
// Load the oAuth2 API
gapi.load('client:auth2', function(){
  // Initialize oAuth2
  var auth2 = gapi.auth2.init({
    client_id:              CLIENT_ID,
    cookie_policy:          'single_host_origin',
    fetch_basic_profile:    true,
    hosted_domain:          HOSTED_DOMAIN,
    immediate:              false,
    scope:                  SCOPES.join(' ')
  });
});
```
This initialization is used by attaching a click handler...

```
var options = new gapi.auth2.SigninOptionsBuilder(),
    scopes  = _g.scopes(),
    i       = 0;
for(i=0; i<scopes.length; i++){
    options.setScope(scopes[i]);
}
gapi.auth2.getAuthInstance().attachClickHandler('googleSignIn', options, onLoginSuccess, onLoginError);
```
Has Google changed anything? Or, any idea why this would be happening on mobile devices only?

Our users have three (very similar) email addresses for the services offered at work (Exchange, Office 365, and Google apps for Education) so they are getting stuck on the first page because they don't know which Email extension to use.

**Comment by TMSCH** [comment] 2017-01-21 00:12
Hi @PDSBGreg,
Thanks for mentioning this issue.
Could you provide a screenshot of the page where the hosted_domain is ignored?
Thanks!
Thomas

**Comment by PDSBGreg** [comment] 2017-01-21 00:38
Here are two screenshots. The first, shows what happens on a PC / Mac / Laptop (in this case a Mac). I am automatically re-directed to our federation SAML server.

![googlesignin-mac](https://cloud.githubusercontent.com/assets/10424675/22170025/286e4718-df47-11e6-9c38-2c62de70983f.png)

This second one shows what happens when I access from a mobile device (iPad or Android ... in this case an iPad).

![googlesignin-ipad](https://cloud.githubusercontent.com/assets/10424675/22170073/ac298586-df47-11e6-8b26-10ce85789330.png)

As you can see from the iPad image, the redirect to our federation server is not happening and I can input any email address into the input box (such as my regular Gmail account), then authorize the app with my regular email account.

In case it matters, the hosted domain account is pdsb.net (a Google for education domain).

We actually have two apps that use gapi for sign-in. Both use the same hosted domain and both have worked fine on all devices until January 17th. Since then, they both have the same issue on mobile.

**Comment by TMSCH** [comment] 2017-01-26 01:01
Thanks for the further information. We are working on a fix, I will update this thread as soon as it is released.

**Comment by PDSBGreg** [comment] 2017-01-26 01:03
Awesome. Thank you.

**Comment by TMSCH** [comment] 2017-01-27 23:20
Hi @PDSBGreg,
We deployed a fix that will display the domain in the email input field.
The flow has been changed recently with the release of the new UI, so the user won't be redirected to your federation SAML server directly, but should be after the email address has been entered.
Could you test on your end and let me know if that works?
Thanks!

**Comment by PDSBGreg** [comment] 2017-01-28 13:05
I'm not seeing it come up with the domain. It's still just an empty line, allowing me to enter any email address. It's it possible that the fix hasn't hit all of the CDN sites?

Also, is there a reason why non mobile devices are directed automatically to the SAML server and mobile are not? Can't it work the same way for both like it used to?

**Comment by PDSBGreg** [comment] 2017-02-01 15:41
I can see the change now. It's still strange to me that it works differently on mobile vs non-mobile (with mobile requiring more typing)...but it's better than it was now that the hosted domain is there and enforced. Thanks for the work-around.

**Comment by TMSCH** [comment] 2017-02-01 23:19
Oh great! I was investigating to see whether it could have been another issue. Good to know it was just delays in deployment.

Does it require more typing in mobile though? Don't you always have to enter the email address once, whether it is on the Google page or your own page?

As far as the difference between mobile and desktop is concerned, the behavior should soon become the same one, what you currently observe in mobile environment. This UX (no automatic redirection) has been chosen because it allows the user to switch account.

**Comment by PDSBGreg** [comment] 2017-02-02 00:09
When we log into our PCs with Active Directory, then go to my app and click on the Google Sign-in button, there actually isn't any typing required at all. The user is auto-directed to our SAML sign-in page, which recognises the user because of being logged into AD, then Google returns the user info to the app (nice an simple). 

On our non-AD connected Macs, clicking the Google Sign in button auto-redirects to our SAML sign-in page where we enter our employee ID and password. (this is how mobile used to work).

On my Mac, if I am signed into my personal Gmail account, it still auto-redirects to our SAML sign-in page because the hosted_domain value doesn't match my person gmail domain, so account switching isn't required at the user level.

I suppose the only time account switching would be an issue (in our case) would be if a user had multiple accounts (which our Active Directory does not allow). I suppose if a hosted domain allowed multiple accounts per person, then account switching would be useful.

Anyway, thanks for explaining the decision. I have a note on our login screen now to let the users know that if they see an extra spot to enter something, that it's their employee ID they need to type in again.

**Comment by TMSCH** [comment] 2017-02-08 02:19
Thanks for the detailed report of these flows. I now understand why it is indeed not ideal in your use case.
If the issue is resolved, could you please close the issue?
Thanks!

**Comment by PDSBGreg** [comment] 2017-02-08 13:15
Sure thing.

**Closed** 2017-02-08 13:16 UTC
