### ISSUE TITLE
Google Drive SDK OAuth2 doesn't remember account selection

### ISSUE THREAD

**Issue by phuwin** [google/google-api-javascript-client#237] opened 2016-08-25 11:43 UTC
If a user has several accounts in their Google, the Account Choose window appears and the user has to choose an account everytime the web is refreshed as it doesn't remember which account the user chose previously.
I have managed to make an OAuth2 authentication using these codes and the configurations guided from [here](https://developers.google.com/api-client-library/javascript/features/authentication#specifying-your-client-id-and-scopes)

```
this.authenticate = function(){
    gapi.load('client:auth2',authorize);
}
function authorize(){
    gapi.client.setApiKey(API_KEY);
    gapi.auth2.init({
        client_id: CLIENT_ID,
        scope: SCOPES
    }).then(function(authResult){
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signIn().then(afterSignIn);
    });
}
function afterSignIn(){
    console.log('authenticated successfully');
    $rootScope.authenticated = true;
    gapi.client.load('drive', 'v3',function(){
        $rootScope.$broadcast('authenticated');
    });
}
```

I have tried these options of `GoogleAuth.signIn()`:

```
auth2.signIn({
            'prompt': '**promtOption**'
  })...
```

`none` : it doesn't authenticate
`login`: does the same as `select_account`
`consent`: does the same as select_account, it additionally asks for offline use permission...
`select_account`: same problem as signing in without options

How can I make the program remember the user selection?

**Comment by TMSCH** [comment] 2017-02-16 03:35
@phuwin when gapi.auth2 initializes, it will automatically load the previously signed in user. If you call `signIn`, this is expected that the user is prompted to select an account. Also, you should call `signIn` synchronously after a user interaction (such as a click) otherwise some browsers will block the popup.

Please refer to the doc for more information: https://developers.google.com/identity/sign-in/web/listeners

**Comment by TMSCH** [comment] 2017-04-13 19:52
Closing this bug as working as intended.

**Closed by TMSCH** 2017-04-13 19:52 UTC
Labels: auth
