### ISSUE TITLE
If there any way how to give live authentication access?

### ISSUE THREAD

**Issue by jack-fdrv** [google/google-api-javascript-client#229] opened 2016-06-23 00:46 UTC
I want to make some js widget to add on site "Contact with me" button. 
It simply should send email via google API. But I dont want the some user will have got pop up with access request for an app. If there any way to make it works permanently without access request each time for new users, sites, domains?

**Comment by TMSCH** [comment] 2017-02-16 03:46
Hi @jack-fdrv this is not possible to authenticate the user without any popup, it goes against the design of OAuth. Closing this issue as working as intended.

**Closed by TMSCH** 2017-02-16 03:46 UTC
