### ISSUE TITLE
gapi.auth.init throws TypeError Cannot read property 'length' of null

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#15] opened 2015-01-07 01:19 UTC
_From [els...@twist.com](https://code.google.com/u/113423050860833505847/) on February 20, 2012 23:33:00_

What steps will reproduce the problem? 1. use gapi.auth.init
2. Get TypeError What is the expected output? What do you see instead? No TypeError

Happy to paste code if it's useful.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=13_

**Comment by TMSCH** [comment] 2017-02-17 17:42
Closing as `gapi.auth` has been deprecated, and the issue is not observed on `gapi.auth2`.

**Closed by TMSCH** 2017-02-17 17:42 UTC
Labels: 2–5 stars, bug, imported, Milestone-GA, Priority-Medium
