### ISSUE TITLE
popup_closed_by_user when authenticating on the Drive Picker API

### ISSUE THREAD

**Issue by raz3r** [google/google-api-javascript-client#409] opened 2018-03-13 16:21 UTC
Hi, the Drive Picker API seems to have some issues. Sometimes when I load the page the following code returns an error.

`window.gapi.auth.authorize({
            'client_id': clientId,
            'scope': scope,
            'immediate': false
          },
          handleAuthResult
        );`

In the handleAuthResult callback I can see the following response. Thing is, popups are not blocked and sometimes the snippet works. I am using the latest version of Google Chrome Beta (Version 65.0.3325.125 (Official Build) beta (64-bit)) but the issue occurs also with non beta version.

`{
  "error": "popup_closed_by_user",
  "status": {
    "signed_in": false,
    "method": null,
    "google_logged_in": false
  },
  "g-oauth-window": null,
  "client_id": "XXX",
  "cookie_policy": "single_host_origin"
}`

EDIT: Same problem with Edge as well.
EDIT: Same problem with Firefox too.

**Comment by TMSCH** [comment] 2018-03-13 17:12
@raz3r do you trigger the call to authorize after the user clicks on a button?

Also, please use [`gapi.auth2.authorize`](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback). `gapi.auth.authorize` is deprecated.

**Comment by raz3r** [comment] 2018-03-14 09:22
I switched to auth2 but I still get the same error. I trigger to authorize automatically, not with a button, though I have tried doing it manually but the problem persists.

**Comment by raz3r** [comment] 2018-03-23 10:00
Any news on this matter? I know Google confirmed it's a general issue.

**Comment by Kontsedal** [comment] 2018-03-29 10:16
I have the same problem, gapi.auth2.authorize doesn't help

**Comment by Kontsedal** [comment] 2018-03-29 12:17
The problem was solved by simulating a click on a button after retrieving of access_token, after that click picker opens without errors

**Comment by TMSCH** [comment] 2018-03-29 15:33
@raz3r you cannot trigger the authorization automatically without a button, when it is expected to open a popup.
@Kontsedal what do you mean by simulating a click? On what, and triggering what?

**Comment by Kontsedal** [comment] 2018-03-29 15:58
@TMSCH 
1) User clicks button (there is a check "if we have auth_token --> just open picker, if not --> we need to get token first")
2) Use gapi.auth.authorize to get auth_token
3) Just execute buttonElement,click()

**Comment by TMSCH** [comment] 2018-03-29 16:40
@Kontsedal before doing buttonElement.click(), you would just call the picker? Could I see the snippet of code?

**Comment by TMSCH** [comment] 2018-03-29 22:03
@Kontsedal could you provide a snippet of code to reproduce the issue, or a live app?

**Comment by Kontsedal** [comment] 2018-03-30 05:11
@TMSCH Here:
`
clickHandler() {
        if (this.authToken) {
            this.createPicker(this.authToken);
        } else {
            this.doAuth(({access_token}) => {
                this.authToken = access_token;
                this.simulateTransferButtonClick();
            });
        }
}

 doAuth(callback) {
        let {config} = this.props;
        window.gapi.auth.authorize({
                client_id: config.clientId,
                scope: SCOPE
            },
            callback
        );
}
simulateTransferButtonClick() {
        this.buttonElement.click();
 }
createPicker(oauthToken) {
        let {config} = this.props;
        if (this.props.createPicker) {
            return this.props.createPicker(window.google, oauthToken)
        }

        const googleViewId = window.google.picker.ViewId[VIEW_ID];
        const view = new window.google.picker.View(googleViewId);

        if (this.props.mimeTypes) {
            view.setMimeTypes(MIME_TYPES)
        }

        if (!view) {
            throw new Error('Can\'t find view by viewId');
        }

        const picker = new window.google.picker.PickerBuilder()
            .addView(view)
            .setOAuthToken(oauthToken)
            .setDeveloperKey(config.apiKey)
            .setCallback(this.onChange.bind(this));

        picker.setOrigin(window.location.origin);
        picker.enableFeature(window.google.picker.Feature.NAV_HIDDEN);
        if (this.props.multiselect) {
            picker.enableFeature(window.google.picker.Feature.MULTISELECT_ENABLED);
        }
        picker.build().setVisible(true);
 }
`
I almost forgot, it happens only if user must to ligin into google account.

**Comment by anudeepjusanu** [comment] 2018-04-18 13:32
Am facing the same issue, Any fix for this?

**Comment by raz3r** [comment] 2018-04-30 08:03
No solution yet? It's been a while...

**Comment by Toftborg** [comment] 2018-05-01 08:33
I can confirm that you receive the error : "error": "popup_closed_by_user"

**Comment by digitalbart** [comment] 2018-05-16 16:28
@dakairus interesting, I will try that I think I have some apis enabled on that project, that I am not using that I can remove.

**Comment by ryanhmaas** [comment] 2018-06-12 14:43
Also getting this error. Any feedback or progress on this?

**Comment by nvioli** [comment] 2018-07-11 00:12
I was having the `(b || "").split is not a function` error, and tracked down (what seems so far to be) a solution in this thread:
https://github.com/google/google-api-javascript-client/issues/13#issuecomment-290129284

> GSI v2 does not accept a list of scope, it has to be a comma-delimited string (e.g. 'scope1 scope2'). > Change to 'https://www.googleapis.com/auth/drive' instead of ['https://www.googleapis.com/auth/drive'] and it will work.

Note that he means **space-delimited**. I was having this problem using the analytics API, and indeed, changing `scope: ['https://www.googleapis.com/auth/analytics.readonly']` to `scope: 'https://www.googleapis.com/auth/analytics.readonly'` appears to have solved it.

**Comment by kongguibin** [comment] 2018-10-18 04:05
This bug should be fixed. More deatil at https://github.com/google/google-api-javascript-client/issues/405.

**Closed by kongguibin** 2018-10-18 04:05 UTC
