### ISSUE TITLE
Uncaught TypeError: this is not a function → on .signOut()

### ISSUE THREAD

**Issue by mesqueeb** [google/google-api-javascript-client#396] opened 2018-02-20 11:20 UTC
<img width="611" alt="2018-02-20 20 19 38" src="https://user-images.githubusercontent.com/3253920/36421335-67006de6-167b-11e8-85a8-499475fe5a8c.png">

**Comment by TMSCH** [comment] 2018-02-20 23:41
What is `setImmediate.js`? I cannot reproduce the issue.

**Comment by mesqueeb** [comment] 2018-02-21 01:27
@TMSCH  Thank you for your aid. After some research I found that [setImmidiate npm module](https://www.npmjs.com/package/setimmediate) is used by webpack.

Maybe it's because of the way I have integrated GAPI in my SPA.

This is my initialisation:
```js
function initGAPI() {
  return new Promise((resolve) => {
    let script = document.createElement('script')
    script.type = 'text/javascript'
    script.src = 'https://apis.google.com/js/api.js'
    script.onload = e => {
      gapi.load('client:auth2', _ => {
        console.log('loaded GAPI')
        gapi.client.init(gapiConfig)
        .then(_ => {
          console.log('initialized GAPI')
          gapi.auth2.getAuthInstance().isSignedIn
            .listen(store.dispatch('gapiAuthListener'))
          store.dispatch('user/updateAuthStatus')
          .then(_ => {
            resolve()
          })
        })
      })
    }
    document.getElementsByTagName('head')[0].appendChild(script)
  })
}
```
If you can give any advice on how to better implement GAPI throughout a `main.js` file only I would be very grateful.
If not I guess I'll take my bug to webpack! : D (I'm not sure how to find out what exactly webpack is doing what wrong where)

**Comment by TMSCH** [comment] 2018-02-21 01:54
I don't think this is due to the way you integrate GAPI. It seems that the implementation of `setImmediate` patched by the npm module breaks the library.

**Comment by TMSCH** [comment] 2018-02-23 20:34
Closing this issue as due to setImmediate.js.

**Closed by TMSCH** 2018-02-23 20:34 UTC
