### ISSUE TITLE
How to use old version of gapi

### ISSUE THREAD

**Issue by yarielg** [google/google-api-javascript-client#597] opened 2020-02-21 19:10 UTC
Now I'm working on gapi with angular app.

`// package.json

{
  ...
  "dependencies": {
    ...
    "@types/gapi": "0.0.39",
    "@types/gapi.auth2": "0.0.50",
    "@types/gapi.client.drive": "^3.0.3"
  }
}

// index.html

<link rel='preconnect' href='https://accounts.google.com' />
<link rel='preconnect' href='https://content.googleapis.com' />
<link rel='preconnect' href='https://apis.google.com' />
<script src="https://apis.google.com/js/platform.js"></script>

// gapi.session.ts

const DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/drive/v3/rest"];
const SCOPES = [
  'https://www.googleapis.com/auth/drive.install',
  'https://www.googleapis.com/auth/drive.file'
].join(' ');

@Injectable()
export class GapiSession {
  googleAuth: gapi.auth2.GoogleAuth;

  constructor(
    private appRepository: AppRepository
  ) {}

  initClient() {
    return new Promise((resolve, reject) => {
      gapi.load('client:auth2', () => {
        return gapi.client.init({
          apiKey: API_KEY,
          clientId: CLIENT_ID,
          discoveryDocs: DISCOVERY_DOCS,
          scope: SCOPES,
        }).then(() => {
          this.googleAuth = gapi.auth2.getAuthInstance();
          resolve();
        });
      });
    });

  }
  get isSignedIn(): boolean {
    return this.googleAuth.isSignedIn.get();
  }

  signInWithToken(data) {
    gapi.auth.setToken(data);

  }

  signIn() {
    return this.googleAuth.signIn({
      prompt: 'select_account'
    }).then((googleUser: gapi.auth2.GoogleUser) => {
      this.appRepository.User.add(googleUser.getBasicProfile());
    });
  }

  signOut(): void {
    this.googleAuth.signOut();
    localStorage.removeItem('fileData');
    localStorage.clear();
  }
}`

This shows the picture following.
![pic1](https://user-images.githubusercontent.com/42778527/75063792-99733480-5520-11ea-9b70-77317b6400a4.png)

I know this is to increase users' security. https://www.blog.google/technology/safety-security/project-strobe/
However, it requires 3 clicks.
As it only wants the required scopes, I want to use the old version of gapi.
Like the picture following.
![pic2](https://user-images.githubusercontent.com/42778527/75064085-38982c00-5521-11ea-8345-d69d223ef224.png)

What do I have to do?
Even if google introduced new version, there should remain the old version.
Thank you.

**Comment by dvanderb** [comment] 2021-03-29 22:09
Old versions of the library are not supported and it is intended behavior that new versions/features are used as they are released.  I am closing this for now, but if you still need help with this question, please reopen.

**Closed by dvanderb** 2021-03-29 22:09 UTC
