### ISSUE TITLE
Need offline access?

### ISSUE THREAD

**Issue by admehta01** [google/google-api-javascript-client#266] opened 2017-01-10 21:12 UTC
We're upgrading from stuff like:
```
gapi.client.load('oauth2', 'v2')...
gapi.client.oauth2.userinfo.get()...
```
to
```
auth2 = gapi.auth2.init({
  client_id: cfg.googleApiClientId,
  cookiepolicy: 'single_host_origin',
  scope: 'profile email',
});

auth2.attachClickHandler...
googleUser.getBasicProfile()...
```
When we do this, users that log in now are being asked for Offline access even though we don't require it. Any ideas why?

**Comment by TMSCH** [comment] 2017-01-10 23:38
Hi @admehta01,
Are you testing this update locally (i.e. with the app running on localhost) or is it observed on the app deployed?
Also, profile and email are the default scopes so you could just do:

```
auth2 = gapi.auth2.init({
  client_id: cfg.googleApiClientId,
  cookie_policy: 'single_host_origin'
});
```

(also changed the `cookie_policy` key to the non deprecated name)

**Comment by admehta01** [comment] 2017-01-10 23:46
Hi @TMSCH,

Thanks for the reply! I've made your changes and tested it on our staging server (not localhost) and get the message there too. Here is the URL of the Google Auth popup, if that helps.
```
https://accounts.google.com/o/oauth2/auth?redirect_uri=storagerelay%3A%2F%2Fhttps%2FMYSITE.com%3Fid%3Dauth7518&response_type=permission+id_token&scope=email+profile+openid&openid.realm&client_id=CLIENT_ID&ss_domain=https%3A%2F%2FMYSITE.com&fetch_basic_profile=true&gsiwebsdk=2&from_login=1&as=-72375acd4010c8e1&authuser=2
```

**Comment by TMSCH** [comment] 2017-01-11 00:22
I can't seem to reproduce the issue myself... Before signing in the account, do you first revoke all the permissions previously granted for this app by this account? Or do you get the consent prompt anyways anytime you sign in the account?

**Comment by admehta01** [comment] 2017-01-11 00:27
We do not revoke all the permissions previously granted. So:

For an existing user (that had given us permissions using the old auth code) this always appears until they click "Allow".

For a new user, it asks for email, etc the first time and then never asks for offline access on subsequent logins.

Here's a screenshot of the popup just to be clear:
![untitled](https://cloud.githubusercontent.com/assets/1946614/21830429/7ea8cda4-d751-11e6-9c78-b3764e245bd0.png)

**Comment by TMSCH** [comment] 2017-01-11 00:50
In your former sign-in flow, did you use the authorization code flow? Or did your app request offline code at some point?

(this is the OAuth2 flow that would retrieve a code, that you then exchange server-side with an access and refresh tokens)

**Comment by admehta01** [comment] 2017-01-11 00:56
Nope, we did not use that flow nor did we request offline codes.

**Comment by TMSCH** [comment] 2017-01-11 02:15
I was finally able to reproduce the issue. I will investigate the cause and come back to you as soon as I find a solution.
Thanks for your inputs!

**Comment by admehta01** [comment] 2017-01-12 17:35
Hi @TMSCH, was wondering if there were any updates? We're trying to switch to the new auth as there are reports of the older auth not working that well on the latest ChromeOS. Thanks!

**Comment by TMSCH** [comment] 2017-01-12 22:19
Hi @admehta01,
I think I found a solution. The issue is that the default scopes have changed from Google Sign-In v1 and v2. The following snippet should work and not prompt for offline access:

```
auth2 = gapi.auth2.init({
  client_id: cfg.googleApiClientId,
  cookie_policy: 'single_host_origin',
  scope: 'profile email',
  fetch_basic_profile: false
});
```

The `fetch_basic_profile` option automatically sets the new default set of scope: 'email profile openid'. However, the GSI v1 would not ask for openid by default, hence the prompt for a new consent.

However, you won't be able to get the profile information of the user by calling `getBasicProfile()` on the signed in user. So if you rely on some user's info like `email` or `displayName` they won't be available. I think it is a bug on our side, I will look into it.

Let me know if that fixes your issue!

**Comment by admehta01** [comment] 2017-01-12 22:58
That did work for me! Thanks a lot for following up on that. But you're right, information we depend on like email and name is not available b/c of `getBasicProfile()` no longer working.

I realize this may be tough, but do you know an ETA of when `getBasicProfile()` would be working? It would help a lot in messaging our users. In the meantime, I will try getting the information we need in the backend as seen here: https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by TMSCH** [comment] 2017-01-17 18:45
It is difficult for me to give you an ETA, but I am currently working on a fix, I'll update this thread as soon as I have more information. Sorry for delaying your migration, and thanks again for reporting this issue!

**Comment by TMSCH** [comment] 2017-01-26 01:02
Hi @admehta01,
The fix has been released, could you try again accessing `getBasicProfile()` in your use case? It should work now.

**Comment by kavithaLK** [comment] 2017-01-29 00:23
Hi, I tried to use this fix in my project but still i am prompted with offline access consent. What am i missing? 

 const params = {
        client_id: clientId,
        cookiepolicy: cookiePolicy,
        login_hint: loginHint,
        hosted_domain: hostedDomain,
        fetch_basic_profile: false,
        scope: "profile email",
      };
 window.gapi.auth2.init(params);

**Comment by TMSCH** [comment] 2017-01-30 17:57
Hi  @kavithaLK,
Could you provide the full code snippet to reproduce the issue? (the `signIn()` call, any metatag elements containing configuration, etc.)
Thanks!

**Comment by kavithaLK** [comment] 2017-01-31 04:46
I am using react-google-login component which 
https://github.com/anthonyjgrove/react-google-login/blob/master/src/index.js
I have set it up to pass fetch_basic_profile=false. 

<GoogleLogin className="loginbutton" style={buttonStyle}
                         fetchBasicProfile={false}
                         scope = "profile email"
                         clientId={GOOGLE_ID}
                        display={"popup"}
                        onSuccess={this.responseGoogle}
                        onFailure={this.responseGoogle} autoLoad
                      />

The url that gets generated : 
https://accounts.google.com/o/oauth2/auth?redirect_uri=storagerelay%3A%2F%2Fhttp%2Fpegeto.me%3Fid%3Dauth670306&response_type=permission%20id_token&scope=profile%20email&openid.realm=&client_id=XXX.apps.googleusercontent.com&ss_domain=http%3A%2F%2Fpegeto.me&prompt=consent&fetch_basic_profile=false&gsiwebsdk=2

Thanks!

**Comment by TMSCH** [comment] 2017-02-01 18:58
The URL seems correct, though the `prompt=consent` should not be there by default. Could you try removing the `&prompt=consent` parameter from the URL (in a text editor), then copy pasting the updated URL (with your actual client_id) in a new tab, and see if you're prompted for the Offline access?

**Comment by TMSCH** [comment] 2017-02-16 02:48
@kavithaLK have you been able to try without the query parameter?

**Comment by TMSCH** [comment] 2017-05-10 16:32
Once the user is signed in, call [`GoogleUser.grantOfflineAccess()`](https://devsite.googleplex.com/identity/sign-in/web/reference#googleusergrantofflineaccessscopes). You can also directly call [`GoogleAuth.grantOfflineAccess()`](https://devsite.googleplex.com/identity/sign-in/web/reference#googleauthgrantofflineaccessoptions) without requiring the user to sign in first. Remember that each time you call this method, the popup will be displayed.

For more information, follow the [guide](https://devsite.googleplex.com/identity/sign-in/web/server-side-flow).

**Comment by Sharma-Ravin** [comment] 2017-05-11 10:51
Hi TMSCH, Your previous answer is very helpful. I tried the code given below. It provide me the code. But not offline access. Please help me with some code.
`var auth2;
function init() {
    gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
            client_id: '<my client id>.apps.googleusercontent.com',
            scope: 'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/spreadsheets'
        });
    });
    $('#signinButton').click(function() {
      auth2.grantOfflineAccess({'redirect_uri' : 'postmessage', 'approval_prompt' : 'force'}).then(onSignIn);
    });
}

function onSignIn(authResult) {
    if (authResult['code']) {
    // Send the code to the server
    }
}`
How this code will work for offline access to google drive sheets

**Comment by TMSCH** [comment] 2017-05-11 16:30
@Sharma-Ravin please refer to the [guide](https://developers.google.com/identity/sign-in/web/server-side-flow) for a detailed explanation of how to use the code in the server (sorry, the link was wrong in my previous comment, I updated it).

**Comment by TMSCH** [comment] 2017-06-30 21:18
Closing the issue as no follow up was given. Please reopen if the issue is still a problem.

**Closed by TMSCH** 2017-06-30 21:18 UTC
Labels: auth

**Comment by urthling** [comment] 2020-09-24 23:14
I can't find anything other than this post -- so posting here.

I seem unable to use grantOfflineAccess with the basic drive scopes.  The popup window appears, after selecting the account to use, the window shows a loading circle for a few seconds and then just closes.

If I use 'grant' instead of 'grantOfflineAccess' -- all is well.  Why is it, that grantOfflineAccess is doing this?  D I need additional or different scopes?

Here's a snippet:

```
let options = new gapi.auth2.SigninOptionsBuilder();
				options.setScope('https://www.googleapis.com/auth/drive.file').setScope('https://www.googleapis.com/auth/drive.appdata')

googleUser = auth2.currentUser.get();
googleUser.grantOfflineAccess(options).then(gDriveSignInCallback, gDriveSignInError);
```

As mentioned, the popup simply closes..

**Comment by urthling** [comment] 2020-09-28 18:18
This appears relevant - this was after changing the perms per [this post](https://stackoverflow.com/questions/55677453/troubleshooting-google-calendar-insert-api-error-insufficient-permission-req) but we're using js gapi

**Comment by urthling** [comment] 2020-09-29 15:48
Ah, when requesting offline access, you don't use the options builder, you simply pass a plain object with the scopes like this:

`googleUser.grantOfflineAccess({scope: 'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.appdata'}).then(gDriveSignInCallback, gDriveSignInError);`
