### ISSUE TITLE
Login hint is not working properly

### ISSUE THREAD

**Issue by cincue** [google/google-api-javascript-client#274] opened 2017-01-26 19:42 UTC
I'm experiencing an odd behavior when dealing with a user that has multiple accounts. It seems the oauth login dialog is remembering the last user that logged in from that location, regardless of the login_hint received.

Here's how you can reproduce it:

1. Log with an account A in google. Make sure you have only logged the account A (i.e.: try it on incognito mode).
2. Log out account A.
3. Go to your google sign-in web implementation. In the oAuth URL complete login_hint param with account B (our wanted account).
4.  Make the request and you will see in the google login form pop-up the Account A completed, prepared to fill the password.

I thought that account B should popup as I was using the login_hint parameter. Am I doing something wrong? Is there anything else needed to make the form start with User B regardless of any previous login history on that session?

**Comment by TMSCH** [comment] 2017-01-26 22:05
HI @cincue,
What library are you using? GSI v1 (gapi.auth) or v2 (gapi.auth2)?

**Comment by cincue** [comment] 2017-01-27 13:17
Hi @TMSCH thanks for the reply. I am using gapi.auth2.

**Comment by TMSCH** [comment] 2017-01-27 16:45
Could you provide a snippet of code to reproduce this behavior? I was not able to reproduce the bug using `GoogleAuth.signIn()`.

**Comment by cincue** [comment] 2017-01-27 18:31
```javascript

startApp();

var googleUser = {};
function startApp(){
  gapi.load('auth2', function(){
    auth2 = gapi.auth2.init({
      client_id: 'xxxxxxxx.apps.googleusercontent.com',
      scope: 'email',
      fetch_basic_profile: false,
      login_hint: '${googleLoginHint}'
   });
   attachSignin(document.getElementById('google-signin-button'));
  });
}

function attachSignin(element){
  auth2.attachClickHandler(element, {},
    function(googleUser){
      document.getElementById('id_token').value = googleUser.getAuthResponse().id_token;
      document.getElementById('form').submit();
    },
    function(error) {
      logFailure();
    }
  );
}
```

Code example from the [documentation page](https://developers.google.com/identity/sign-in/web/build-button).

**Comment by TMSCH** [comment] 2017-01-27 21:37
I am not able to reproduce this issue with your code... What are you passing as login hint? An email address?

**Comment by cincue** [comment] 2017-01-30 14:36
Yes, I am passing an email address.

This should happen in the same browser session. Something that I see is that when I logout account A, I get redirected to a login screen where it's already showing me the last logged user (Account A), and asking directly for a password (and that's exactly the same screen I see when attempting to log account B).

Could it be that remembering the last user logged in when there's only one user session takes precedence over the login hint?

**Comment by TMSCH** [comment] 2017-01-30 18:05
Hi @cincue, I think I don't understand properly the method to reproduce the issue, as I'm not able to. When you say "log out" from the account, do you mean `signOut()` using the library or logging the user out from https://accounts.google.com?

**Comment by cincue** [comment] 2017-01-30 18:49
I mean logging the user out from https://accounts.google.com

In short:
1- Log user A in https://accounts.google.com
2- Log out user A from https://accounts.google.com
3- ````signIn()```` with login_hint = user B (or use my code above instead)

Make sure you reproduce it in the same session (start a new session, try it on incognito mode)

**Comment by TMSCH** [comment] 2017-01-31 00:11
Thanks for the further information! I was finally able to reproduce the issue, I was doing something wrong before. I'll investigate the issue and come back to you as soon as I have more info!

**Comment by cincue** [comment] 2017-01-31 12:57
Great! @TMSCH I hope it can be fixed, let me know any update. Thanks!

**Comment by TMSCH** [comment] 2017-03-03 19:08
Hi @cincue! This issue has been fixed and released. Let me know if that works for you!

**Comment by cincue** [comment] 2017-03-03 20:38
Fantastic! @TMSCH It works perfect now! Thanks

**Comment by TMSCH** [comment] 2017-03-03 22:23
Glad it works! Closing this issue.

**Closed by TMSCH** 2017-03-03 22:23 UTC
Labels: auth
